"""
PR Generator -- creates structured pull request payloads from auto-fix results.
Formats diffs, titles, and descriptions in GitHub/GitLab PR format.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class PullRequestPayload:
    title: str
    body: str
    branch_name: str
    base_branch: str
    labels: list[str]
    files: list[dict[str, Any]] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "body": self.body,
            "branch_name": self.branch_name,
            "base_branch": self.base_branch,
            "labels": self.labels,
            "files_changed": len(self.files),
            "files": self.files,
            "created_at": self.created_at.isoformat(),
        }

    def to_github_payload(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "body": self.body,
            "head": self.branch_name,
            "base": self.base_branch,
            "labels": self.labels,
        }


class PRGenerator:
    """
    Generates well-structured PR descriptions from pipeline fix results.
    """

    def from_security_fixes(
        self,
        fixes: list[dict[str, Any]],
        run_id: str,
        base_branch: str = "main",
    ) -> PullRequestPayload:
        critical = [f for f in fixes if f.get("severity") in ("CRITICAL", "HIGH")]
        title = self._security_title(fixes)
        body = self._security_body(fixes, run_id)
        labels = ["security", "automated-fix", "intellipipeline"]
        if critical:
            labels.append("priority:high")

        return PullRequestPayload(
            title=title,
            body=body,
            branch_name=f"intellipipeline/security-fix-{run_id[:8]}",
            base_branch=base_branch,
            labels=labels,
            files=[{"path": f.get("file_path", "unknown"), "changes": f.get("fixed_line", "")} for f in fixes],
        )

    def from_config_fixes(
        self,
        fixes: list[dict[str, Any]],
        run_id: str,
        base_branch: str = "main",
    ) -> PullRequestPayload:
        title = f"fix(config): resolve {len(fixes)} configuration issue(s) [IntelliPipeline]"
        body = self._config_body(fixes, run_id)
        return PullRequestPayload(
            title=title,
            body=body,
            branch_name=f"intellipipeline/config-fix-{run_id[:8]}",
            base_branch=base_branch,
            labels=["config", "automated-fix", "intellipipeline"],
        )

    def from_optimizer_suggestions(
        self,
        suggestions: list[dict[str, Any]],
        savings: dict[str, Any],
        run_id: str,
        base_branch: str = "main",
    ) -> PullRequestPayload:
        monthly = savings.get("estimated_monthly_cost_saving_usd", 0)
        title = f"perf(ci): optimise pipeline -- save ~${monthly:.0f}/month [IntelliPipeline]"
        body = self._optimizer_body(suggestions, savings, run_id)
        return PullRequestPayload(
            title=title,
            body=body,
            branch_name=f"intellipipeline/pipeline-optimize-{run_id[:8]}",
            base_branch=base_branch,
            labels=["performance", "ci-cd", "automated-fix", "intellipipeline"],
        )

    # ---- Body builders -------------------------------------------------------

    def _security_title(self, fixes: list[dict]) -> str:
        types = list({f.get("secret_type") or f.get("title") or "issue" for f in fixes[:3]})
        short = ", ".join(t[:30] for t in types[:2])
        return f"fix(security): resolve {len(fixes)} finding(s) -- {short} [IntelliPipeline]"

    def _security_body(self, fixes: list[dict], run_id: str) -> str:
        lines = [
            "## Security Fixes -- Generated by IntelliPipeline",
            "",
            f"> Run ID: `{run_id}` | Auto-generated | Review before merging",
            "",
            "### Findings Addressed",
            "",
        ]
        for f in fixes:
            sev = f.get("severity", "UNKNOWN")
            title = f.get("title") or f.get("description") or f.get("secret_type", "Issue")
            rule = f.get("rule_id", "")
            lines.append(f"- **[{sev}]** `{rule}` -- {title}")
            if f.get("remediation"):
                lines.append(f"  - {f['remediation']}")

        lines += [
            "",
            "### Changes Made",
            "",
        ]
        for f in fixes:
            if f.get("original_line") and f.get("fixed_line"):
                lines += [
                    f"**{f.get('file_path', 'unknown')}** line {f.get('line_number', '?')}:",
                    "```diff",
                    f"- {f['original_line'].strip()}",
                    f"+ {f['fixed_line'].strip()}",
                    "```",
                    "",
                ]

        lines += [
            "### Checklist",
            "- [ ] Review each change manually",
            "- [ ] Rotate any exposed credentials immediately",
            "- [ ] Run test suite after applying",
            "- [ ] Update secrets in your secrets manager",
            "",
            "---",
            "_Generated by [IntelliPipeline](https://github.com/HarshalSant/cognitive-mdm)_",
        ]
        return "\n".join(lines)

    def _config_body(self, fixes: list[dict], run_id: str) -> str:
        lines = [
            "## Configuration Fixes -- Generated by IntelliPipeline",
            "",
            f"> Run ID: `{run_id}`",
            "",
            "| Rule | Severity | Issue | Config Type |",
            "|------|----------|-------|-------------|",
        ]
        for f in fixes:
            lines.append(
                f"| `{f.get('rule_id','')}` | {f.get('severity','')} | "
                f"{f.get('title','')} | {f.get('config_type','')} |"
            )
        lines += [
            "",
            "---",
            "_Generated by [IntelliPipeline](https://github.com/HarshalSant/cognitive-mdm)_",
        ]
        return "\n".join(lines)

    def _optimizer_body(
        self, suggestions: list[dict], savings: dict, run_id: str
    ) -> str:
        per_run = savings.get("per_run_savings_seconds", 0)
        monthly_min = savings.get("monthly_savings_minutes", 0)
        monthly_cost = savings.get("estimated_monthly_cost_saving_usd", 0)
        lines = [
            "## Pipeline Optimisation -- Generated by IntelliPipeline",
            "",
            f"> Run ID: `{run_id}`",
            "",
            "### Estimated Impact",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Time saved per run | **{per_run}s** |",
            f"| Monthly CI minutes saved | **{monthly_min:.0f} min** |",
            f"| Estimated monthly cost saving | **${monthly_cost:.2f}** |",
            "",
            "### Suggestions",
            "",
        ]
        for s in suggestions:
            lines.append(f"#### `{s['rule_id']}` [{s['priority']}] -- {s['title']}")
            lines.append(f"{s['description']}")
            lines.append(f"- **Impact:** {s['impact']}")
            lines.append(f"- **Estimated savings:** {s['estimated_savings_seconds']}s/run")
            if s.get("suggested_snippet"):
                lines += ["```yaml", s["suggested_snippet"], "```"]
            lines.append("")
        lines += [
            "---",
            "_Generated by [IntelliPipeline](https://github.com/HarshalSant/cognitive-mdm)_",
        ]
        return "\n".join(lines)
